export const category = {
  middleSchool : 'Middle School',
  highSchool : 'High School',
}

export const step = {
  level01: 'Level 01',
  level02: 'Level 02',
}

export const words = [
  {
    id:1,
    category: category.middleSchool,
    step: step.level01,
    english: 'library',
    korean: '도서관',
    explanation: '(대저택의)서재,(개인이 가진 책,시디 등의) 장서[수집품]들',
  },
  {
    id:2,
    category: category.middleSchool,
    step: step.level01,
    english: 'station',
    korean: '기차역',
    explanation: '(버스)정거장[정류장], 특정한 서비스가 제공되거나 이루어지는 장소건물',
  },
  {
    id:3,
    category: category.middleSchool,
    step: step.level01,
    english: 'carry',
    korean: '나르다',
    explanation: '휴대하다, 가지고 다니다, (물, 전기 등을) 실어 나르다[전달하다]',
  },
  {
    id:4,
    category: category.middleSchool,
    step: step.level01,
    english: 'speak',
    korean: '말하다',
    explanation: '이야기하다, (어떤 내용을) 말하다[언급/기술하다]',
  },
  {
    id:5,
    category: category.middleSchool,
    step: step.level01,
    english: 'put',
    korean: '놓다',
    explanation: '(특정한 장소,위치에) 놓다[두다/넣다/얹다], (사물을 억지로)밀어 넣다',
  },
  {
    id:6,
    category: category.middleSchool,
    step: step.level02,
    english: 'wash',
    korean: '씻다',
    explanation: '(몸을)씻다, 물에 씻을 수 있다[씻기다]',
  },
  {
    id:7,
    category: category.middleSchool,
    step: step.level02,
    english: 'tired',
    korean: '피로한',
    explanation: '피곤한, 지친, (사람이 ~에) 실증난[물린/지긋지긋한]',
  },
  {
    id:8,
    category: category.middleSchool,
    step: step.level02,
    english: 'trip',
    korean: '여행',
    explanation: '(특히 짧고, 관광이나 어떤 특정한 목적을 위한 것), 이동[오고감]',
  },
  {
    id:9,
    category: category.middleSchool,
    step: step.level02,
    english: 'show',
    korean: '보여주다',
    explanation: '증명하다, (...에게) 보여주다, 제시하다',
  },
  {
    id:10,
    category: category.middleSchool,
    step: step.level02,
    english: 'bring',
    korean: '가져오다',
    explanation: '데려오다, 가져다[제공해] 주다, 야기하다',
  },
  {
    id:11,
    category: category.highSchool,
    step: step.level01,
    english: 'together',
    korean: '함께',
    explanation: '같이, (결혼 등으로)함께 하여',
  },
  {
    id:12,
    category: category.highSchool,
    step: step.level01,
    english: 'each',
    korean: '각각',
    explanation: '각자의',
  },
  {
    id:13,
    category: category.highSchool,
    step: step.level01,
    english: 'worry',
    korean: '걱정하다',
    explanation: '걱정[불안]하게 만들다, 성가시게 하다',
  },
  {
    id:14,
    category: category.highSchool,
    step: step.level01,
    english: 'learn',
    korean: '배우다',
    explanation: '학습하다, ~을 알게되다, 외우다, 암기하다',
  },
  {
    id:15,
    category: category.highSchool,
    step: step.level01,
    english: 'visit',
    korean: '방문하다',
    explanation: '(사람장소를) 찾아가다, 체류하다, 머물다',
  },
  {
    id:16,
    category: category.highSchool,
    step: step.level02,
    english: 'read',
    korean: '읽다',
    explanation: '(글기호 등을) 판독하다, (눈으로)읽다, (소리내어)읽다, 읽어주다',
  },
  {
    id:17,
    category: category.highSchool,
    step: step.level02,
    english: 'listen',
    korean: '듣다',
    explanation: '귀 기울이다, (남의 충고 등을)듣다',
  },
  {
    id:18,
    category: category.highSchool,
    step: step.level02,
    english: 'dear',
    korean: '(...가) 사랑하는',
    explanation: '(...에게) 소중한, (편지 첫 부분에 수신자의 이름이나 직책 앞에 써서)...에게, 비싼',
  },
  {
    id:19,
    category: category.highSchool,
    step: step.level02,
    english: 'yesterday',
    korean: '어제',
    explanation: '과거, 어제',
  },
  {
    id:20,
    category: category.highSchool,
    step: step.level02,
    english: 'theater',
    korean: '극장',
    explanation: '(미)에서는 -ter가 많이 쓰이나, 극장 이름에는 -tre가 흔함, (연극, 영화의) 관객',
  },
]
