export const category = {
  middleSchool: 'Middle School',
  highSchool: 'High School',
  myWords: 'My Words'
}

export const step = {
  level01: 'Level 01',
  level02: 'Level 02',
}

export const words = [
  {
    id:1,
    category: category.middleSchool,
    step: step.level01,
    english: 'library',
    korean: '図書館',
    explanation: '（大邸宅の）書斎、（個人が持つ本、シディなどの）蔵書[収集品]',
  },
  {
    id:2,
    category: category.middleSchool,
    step: step.level01,
    english: 'station',
    korean: '駅',
    explanation: '（バス）停留所[停留所]、特定のサービスが提供または行われる場所建物',
  },
  {
    id:3,
    category: category.middleSchool,
    step: step.level01,
    english: 'carry',
    korean: '運ぶ',
    explanation: '持ち運ぶ、持っています、(水、電気等を)運ぶ[伝達する]',
  },
  {
    id:4,
    category: category.middleSchool,
    step: step.level01,
    english: 'speak',
    korean: '話す',
    explanation: '話す、（ある内容を）話す[言葉/技術する]',
  },
  {
    id:5,
    category: category.middleSchool,
    step: step.level01,
    english: 'put',
    korean: '置く',
    explanation: '（特定の場所、位置に）置く[置く/入れる/載せる]、(物を無理に)押し込む',
  },
  {
    id:6,
    category: category.middleSchool,
    step: step.level02,
    english: 'wash',
    korean: '洗う',
    explanation: '（体を）洗う、水で洗える[洗う]',
  },
  {
    id:7,
    category: category.middleSchool,
    step: step.level02,
    english: 'tired',
    korean: '疲れた',
    explanation: '疲れた、疲れた、（人が〜に）実証済み',
  },
  {
    id:8,
    category: category.middleSchool,
    step: step.level02,
    english: 'trip',
    korean: '旅行',
    explanation: '（特に短く、観光やある特定の目的のためのもの）、移動【お越し】',
  },
  {
    id:9,
    category: category.middleSchool,
    step: step.level02,
    english: 'show',
    korean: '見せる',
    explanation: '証明する、(...に)示す、提示する',
  },
  {
    id:10,
    category: category.middleSchool,
    step: step.level02,
    english: 'bring',
    korean: '持ってくる',
    explanation: '連れてくる、持ってくる',
  },
  {
    id:11,
    category: category.highSchool,
    step: step.level01,
    english: 'together',
    korean: '一緒に',
    explanation: '一緒に、（結婚などで）一緒に',
  },
  {
    id:12,
    category: category.highSchool,
    step: step.level01,
    english: 'each',
    korean: 'それぞれ',
    explanation: 'それぞれの',
  },
  {
    id:13,
    category: category.highSchool,
    step: step.level01,
    english: 'worry',
    korean: '心配',
    explanation: '心配[不安]にする、迷惑をかける',
  },
  {
    id:14,
    category: category.highSchool,
    step: step.level01,
    english: 'learn',
    korean: '学ぶ',
    explanation: '学習する、〜を知る、覚える、暗記する',
  },
  {
    id:15,
    category: category.highSchool,
    step: step.level01,
    english: 'visit',
    korean: '訪問',
    explanation: '（人の場所を）訪れる、滞在する、滞在する',
  },
  {
    id:16,
    category: category.highSchool,
    step: step.level02,
    english: 'read',
    korean: '読む',
    explanation: '（文字などを）読む、（目で）読む、（声を出して）読む、読む',
  },
  {
    id:17,
    category: category.highSchool,
    step: step.level02,
    english: 'listen',
    korean: '聞く',
    explanation: '耳を傾ける、（男のアドバイスなどを）聞く',
  },
  {
    id:18,
    category: category.highSchool,
    step: step.level02,
    english: 'dear',
    korean: '親愛なる',
    explanation: '（…に）大切な、（手紙の最初の部分に受信者の名前や役職の前に書いて）…に、高価',
  },
  {
    id:19,
    category: category.highSchool,
    step: step.level02,
    english: 'yesterday',
    korean: '昨日',
    explanation: '過去、昨日',
  },
  {
    id:20,
    category: category.highSchool,
    step: step.level02,
    english: 'theater',
    korean: '劇場',
    explanation: '(米)では-terが多く使われ、劇場名には-treが一般的で、(演劇、映画の)観客',
  },
]
